version: "3"
services:
 opensearch:
   build: .
   ports:
     - 9200:9200
     - 9600:9600
   environment:
     - cluster.name=opensearch-test
     - node.name=opensearch-node1
     - discovery.type=single-node
     - bootstrap.memory_lock=true
     - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
     - "DISABLE_INSTALL_DEMO_CONFIG=true"
     - "DISABLE_SECURITY_PLUGIN=true"
   ulimits:
     memlock:
       soft: -1
       hard: -1
     nofile:
       soft: 65536
       hard: 65536
   volumes:
     - opensearch-data:/usr/share/opensearch/data
   networks:
     - opensearch-net

 opensearch-dashboards:
   image: opensearchproject/opensearch-dashboards:latest
   container_name: opensearch-dashboards
   ports:
     - 5601:5601
   expose:
     - "5601"
   environment:
     - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
     - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
   networks:
     - opensearch-net

volumes:
 opensearch-data:

networks:
 opensearch-net: